/**
 * Extracts woff2 fonts embedded in sticker.svg, decompresses them to TTF,
 * and writes src/fonts.ts with the base64-encoded TTF data so jsPDF can
 * embed them in vector PDFs.
 *
 * Usage: node scripts/extract-fonts.mjs
 */
import fs from "fs";
import { decompress } from "wawoff2";

const svg = fs.readFileSync("src/assets/sticker.svg", "utf-8");

function extractBase64(fontFamily) {
  const re = new RegExp(
    `font-family:\\s*'${fontFamily}';\\s*src:\\s*url\\('data:application/x-font-woff2;base64,([A-Za-z0-9+/=]+)'\\)`
  );
  const m = svg.match(re);
  if (!m) throw new Error(`Could not find @font-face for '${fontFamily}'`);
  return m[1];
}

async function woff2ToTtfBase64(woff2Base64) {
  const woff2Buf = Buffer.from(woff2Base64, "base64");
  const ttfBuf = await decompress(woff2Buf);
  return Buffer.from(ttfBuf).toString("base64");
}

const dottyTtf = await woff2ToTtfBase64(extractBase64("DOTTY"));
const ocrTtf = await woff2ToTtfBase64(extractBase64("OCR"));

const output = `// Auto-generated by scripts/extract-fonts.mjs — do not edit manually.
// TTF font data converted from the woff2 @font-face declarations in sticker.svg.
export const DOTTY_TTF_BASE64 = "${dottyTtf}";\nexport const OCR_TTF_BASE64 = "${ocrTtf}";\n`;

fs.writeFileSync("src/fonts.ts", output);
console.log(
  `Done — wrote src/fonts.ts (DOTTY: ${dottyTtf.length} chars, OCR: ${ocrTtf.length} chars)`
);
